name: cnubot_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  get: ^4.6.5
  url_launcher: ^6.1.5
  cached_network_image: ^3.2.1
  shimmer: ^2.0.0
  intl: ^0.17.0
  device_info_plus: ^3.2.4
  flutter_screenutil: ^5.5.3+2
  flutter_local_notifications: ^9.7.0
  flutter_native_timezone: ^2.0.0
  carousel_slider: ^4.1.1
  flutter_dotenv: ^5.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_launcher_icons: ^0.10.0
  dio: ^4.0.6
  font_awesome_flutter: ^10.2.1
  alice: ^0.2.5
  dio_cache_interceptor: ^3.3.1
  flutter_svg: ^1.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  build_runner: ^2.2.0

flutter:  
  uses-material-design: true

  assets:
    - assets/images/common/
    - assets/config/
